"use strict";

function isFiniteNumber(value) {
    return typeof value === "number" && Number.isFinite(value);
}

function validateTuple(tuple, expectedSize, label, index) {
    if (!Array.isArray(tuple) || tuple.length < expectedSize) {
        throw new Error(`${label}[${index}] must be an array with ${expectedSize} numbers.`);
    }
    for (let i = 0; i < expectedSize; i++) {
        if (!isFiniteNumber(tuple[i])) {
            throw new Error(`${label}[${index}][${i}] must be a finite number.`);
        }
    }
}

function validateFace(face, index, vertexCount) {
    if (!Array.isArray(face) || face.length < 3) {
        throw new Error(`faces[${index}] must be a triangle tuple.`);
    }
    for (let i = 0; i < 3; i++) {
        const vertexIndex = face[i];
        if (!Number.isInteger(vertexIndex)) {
            throw new Error(`faces[${index}][${i}] must be an integer index.`);
        }
        if (vertexIndex < 0 || vertexIndex >= vertexCount) {
            throw new Error(`faces[${index}][${i}] is out of range for vertices.`);
        }
    }
}

function encodeObjMesh({ vertices, faces, normals = null, uvs = null }) {
    if (!Array.isArray(vertices) || vertices.length === 0) {
        throw new Error("vertices must be a non-empty array.");
    }
    if (!Array.isArray(faces) || faces.length === 0) {
        throw new Error("faces must be a non-empty array.");
    }

    for (let i = 0; i < vertices.length; i++) {
        validateTuple(vertices[i], 3, "vertices", i);
    }

    const hasNormals = Array.isArray(normals) && normals.length > 0;
    if (hasNormals) {
        if (normals.length !== vertices.length) {
            throw new Error("normals length must match vertices length.");
        }
        for (let i = 0; i < normals.length; i++) {
            validateTuple(normals[i], 3, "normals", i);
        }
    }

    const hasUvs = Array.isArray(uvs) && uvs.length > 0;
    if (hasUvs) {
        if (uvs.length !== vertices.length) {
            throw new Error("uvs length must match vertices length.");
        }
        for (let i = 0; i < uvs.length; i++) {
            validateTuple(uvs[i], 2, "uvs", i);
        }
    }

    for (let i = 0; i < faces.length; i++) {
        validateFace(faces[i], i, vertices.length);
    }

    const lines = ["# Generated by Sof mesh-service"];

    for (const vertex of vertices) {
        lines.push(`v ${vertex[0]} ${vertex[1]} ${vertex[2]}`);
    }

    if (hasUvs) {
        for (const uv of uvs) {
            lines.push(`vt ${uv[0]} ${uv[1]}`);
        }
    }

    if (hasNormals) {
        for (const normal of normals) {
            lines.push(`vn ${normal[0]} ${normal[1]} ${normal[2]}`);
        }
    }

    for (const face of faces) {
        const a = face[0] + 1;
        const b = face[1] + 1;
        const c = face[2] + 1;

        if (hasUvs && hasNormals) {
            lines.push(`f ${a}/${a}/${a} ${b}/${b}/${b} ${c}/${c}/${c}`);
        } else if (hasUvs) {
            lines.push(`f ${a}/${a} ${b}/${b} ${c}/${c}`);
        } else if (hasNormals) {
            lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
        } else {
            lines.push(`f ${a} ${b} ${c}`);
        }
    }

    return Buffer.from(`${lines.join("\n")}\n`, "utf8");
}

module.exports = {
    encodeObjMesh
};
