"use strict";

const fs = require("fs");
const crypto = require("crypto");
const toml = require("smol-toml");

const { assertPackageAlias, assertProjectFolder } = require("./safe-path");

function hashText(text) {
  return `sha256:${crypto.createHash("sha256").update(text).digest("hex")}`;
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function normalizeLockEntry(rawEntry, index) {
  const label = `sof.lock [[package]] entry #${index}`;
  if (!isPlainObject(rawEntry)) {
    throw new Error(`${label} must be a TOML table.`);
  }

  for (const field of ["name", "alias", "version", "source", "path", "checksum"]) {
    if (typeof rawEntry[field] !== "string" || rawEntry[field].trim() === "") {
      throw new Error(`${label}: "${field}" must be a non-empty string.`);
    }
  }

  // sof.lock is as untrusted as sof.toml: package install deletes and writes at path/alias.
  assertPackageAlias(rawEntry.alias.trim(), `${label}: "alias"`);
  assertProjectFolder(rawEntry.path.trim(), `${label}: "path"`);

  return {
    name: rawEntry.name.trim(),
    alias: rawEntry.alias.trim(),
    version: rawEntry.version.trim(),
    source: rawEntry.source.trim(),
    path: rawEntry.path.trim(),
    checksum: rawEntry.checksum.trim(),
  };
}

function readLockfile(lockfilePath) {
  if (!fs.existsSync(lockfilePath)) {
    return {
      exists: false,
      entries: [],
    };
  }

  const text = fs.readFileSync(lockfilePath, "utf8");
  const hash = hashText(text);
  if (!text.trim()) {
    return {
      exists: true,
      hash,
      entries: [],
    };
  }

  let parsed;
  try {
    parsed = toml.parse(text);
  } catch (err) {
    throw new Error(`Failed to parse lockfile at ${lockfilePath}: ${err.message}`);
  }

  const rawEntries = parsed.package;
  if (rawEntries === undefined) {
    return {
      exists: true,
      hash,
      entries: [],
    };
  }

  if (!Array.isArray(rawEntries)) {
    throw new Error(`Lockfile field "package" must be an array of tables.`);
  }

  return {
    exists: true,
    hash,
    entries: rawEntries.map((entry, index) => normalizeLockEntry(entry, index + 1)),
  };
}

function escapeTomlString(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function writeLockfile(lockfilePath, entries) {
  const sortedEntries = (entries || []).slice().sort((a, b) => {
    const pathCompare = a.path.localeCompare(b.path);
    if (pathCompare !== 0) {
      return pathCompare;
    }

    const aliasCompare = a.alias.localeCompare(b.alias);
    if (aliasCompare !== 0) {
      return aliasCompare;
    }

    return a.name.localeCompare(b.name);
  });

  const lines = ["# Auto-generated by sof install. Do not edit.", ""];
  for (const entry of sortedEntries) {
    lines.push("[[package]]");
    lines.push(`name = "${escapeTomlString(entry.name)}"`);
    lines.push(`alias = "${escapeTomlString(entry.alias)}"`);
    lines.push(`version = "${escapeTomlString(entry.version)}"`);
    lines.push(`source = "${escapeTomlString(entry.source)}"`);
    lines.push(`path = "${escapeTomlString(entry.path)}"`);
    lines.push(`checksum = "${escapeTomlString(entry.checksum)}"`);
    lines.push("");
  }

  // Left untouched when nothing changed, so file watchers don't fire on a no-op install.
  const text = `${lines.join("\n")}\n`;
  if (!fs.existsSync(lockfilePath) || fs.readFileSync(lockfilePath, "utf8") !== text) {
    fs.writeFileSync(lockfilePath, text, "utf8");
  }

  return { hash: hashText(text) };
}

module.exports = {
  readLockfile,
  writeLockfile,
};
