"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");

const LOCAL_SOF_DIRECTORY = path.join(os.homedir(), ".sof");
const LOCAL_UPLOADER_ENV_PATH = path.join(LOCAL_SOF_DIRECTORY, "uploader.env");
const LEGACY_UPLOADER_ENV_PATH = path.join(__dirname, ".env");

const PLACEHOLDER_ENV_VALUES = {
  ROBLOX_API_KEY: new Set([
    "your_api_key_here",
    "<your_api_key>",
  ]),
  ROBLOSECURITY: new Set([
    "your_cookie_value_here",
    "your_roblosecurity_here",
    "<your_roblosecurity>",
  ]),
  ROBLOX_CREATOR_ID: new Set([
    "your_creator_id_here",
    "your_user_id_here",
    "your_group_id_here",
    "<your_creator_id>",
  ]),
};

function isPlaceholderEnvValue(key, value) {
  const normalizedKey = String(key || "").trim();
  const normalizedValue = String(value || "").trim().toLowerCase();
  if (!normalizedValue) {
    return false;
  }

  const placeholders = PLACEHOLDER_ENV_VALUES[normalizedKey];
  if (!placeholders) {
    return false;
  }

  return placeholders.has(normalizedValue);
}

function sanitizeApiKey(value) {
  const output = String(value || "").trim();
  if (!output || isPlaceholderEnvValue("ROBLOX_API_KEY", output)) {
    return "";
  }
  return output;
}

function sanitizeRoblosecurity(value) {
  let output = String(value || "").trim();

  if (output.startsWith(".ROBLOSECURITY=")) {
    output = output.slice(".ROBLOSECURITY=".length);
  }

  if (output.endsWith(";")) {
    output = output.slice(0, -1);
  }

  if (isPlaceholderEnvValue("ROBLOSECURITY", output)) {
    return "";
  }

  return output.trim();
}

function assertSingleLine(value, fieldName) {
  if (/[\r\n]/.test(value)) {
    throw new Error(`${fieldName} must be a single line value.`);
  }
}

function sanitizeCreatorId(value) {
  const output = String(value || "").trim();
  if (!output) {
    return "";
  }
  if (isPlaceholderEnvValue("ROBLOX_CREATOR_ID", output)) {
    return "";
  }
  if (!/^\d+$/.test(output)) {
    throw new Error(`ROBLOX_CREATOR_ID must be numeric: ${value}`);
  }
  return output;
}

function parseEnvLine(line) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) {
    return null;
  }

  const separatorIndex = trimmed.indexOf("=");
  if (separatorIndex <= 0) {
    return null;
  }

  const key = trimmed.slice(0, separatorIndex).trim();
  if (!key) {
    return null;
  }

  let value = trimmed.slice(separatorIndex + 1).trim();
  const hasDoubleQuotes = value.startsWith("\"") && value.endsWith("\"");
  const hasSingleQuotes = value.startsWith("'") && value.endsWith("'");
  if ((hasDoubleQuotes || hasSingleQuotes) && value.length >= 2) {
    value = value.slice(1, -1);
  }

  return { key, value };
}

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  const content = fs.readFileSync(filePath, "utf8");
  const lines = content.split(/\r?\n/);

  for (const line of lines) {
    const parsed = parseEnvLine(line);
    if (!parsed) {
      continue;
    }

    if (
      process.env[parsed.key] === undefined &&
      !isPlaceholderEnvValue(parsed.key, parsed.value)
    ) {
      process.env[parsed.key] = parsed.value;
    }
  }
}

function loadUploaderEnv() {
  loadEnvFile(LOCAL_UPLOADER_ENV_PATH);
  loadEnvFile(LEGACY_UPLOADER_ENV_PATH);
}

function writeUploaderEnv({ apiKey, roblosecurity, creatorId }) {
  const normalizedApiKey = sanitizeApiKey(apiKey);
  const normalizedRoblosecurity = sanitizeRoblosecurity(roblosecurity);
  const normalizedCreatorId = sanitizeCreatorId(creatorId);

  if (!normalizedApiKey) {
    throw new Error("ROBLOX_API_KEY cannot be empty.");
  }
  if (!normalizedRoblosecurity) {
    throw new Error("ROBLOSECURITY cannot be empty.");
  }
  if (!normalizedCreatorId) {
    throw new Error("ROBLOX_CREATOR_ID cannot be empty.");
  }

  assertSingleLine(normalizedApiKey, "ROBLOX_API_KEY");
  assertSingleLine(normalizedRoblosecurity, "ROBLOSECURITY");
  assertSingleLine(normalizedCreatorId, "ROBLOX_CREATOR_ID");

  const envBody =
    `# Auto-generated by "sof run uploader env"\n` +
    `ROBLOX_API_KEY=${normalizedApiKey}\n` +
    `ROBLOSECURITY=${normalizedRoblosecurity}\n` +
    `ROBLOX_CREATOR_ID=${normalizedCreatorId}\n`;

  fs.mkdirSync(LOCAL_SOF_DIRECTORY, { recursive: true });
  fs.writeFileSync(LOCAL_UPLOADER_ENV_PATH, envBody, {
    encoding: "utf8",
    mode: 0o600,
  });

  return LOCAL_UPLOADER_ENV_PATH;
}

module.exports = {
  LOCAL_UPLOADER_ENV_PATH,
  loadUploaderEnv,
  sanitizeApiKey,
  sanitizeCreatorId,
  sanitizeRoblosecurity,
  writeUploaderEnv,
};
