"use strict";

const fs = require("fs");
const path = require("path");
const toml = require("smol-toml");

const TOOL_ALIAS_PATTERN = /^[A-Za-z0-9_.-]+$/;
const TOOL_SPEC_PATTERN = /^(github:)?[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+@.+$/;

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function normalizeAlias(alias, contextLabel) {
  if (typeof alias !== "string" || alias.trim() === "") {
    throw new Error(`${contextLabel}: tool alias must be a non-empty string.`);
  }

  const normalized = alias.trim();
  if (!TOOL_ALIAS_PATTERN.test(normalized)) {
    throw new Error(
      `${contextLabel}: tool alias "${normalized}" may only contain letters, numbers, ".", "_" and "-".`
    );
  }

  return normalized;
}

function normalizeSpecifier(specifier, contextLabel, aliasLabel) {
  if (typeof specifier !== "string" || specifier.trim() === "") {
    throw new Error(`${contextLabel}: [tools].${aliasLabel} must be a non-empty string.`);
  }

  const normalized = specifier.trim();
  if (!TOOL_SPEC_PATTERN.test(normalized)) {
    throw new Error(
      `${contextLabel}: [tools].${aliasLabel} must use "owner/repo@version" (or "github:owner/repo@version").`
    );
  }

  return normalized;
}

function readConfigFile(configPathArg) {
  const configPath = path.resolve(configPathArg || "sof.toml");
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config file does not exist: ${configPath}`);
  }

  const configText = fs.readFileSync(configPath, "utf8");
  let parsed;
  try {
    parsed = toml.parse(configText);
  } catch (err) {
    throw new Error(`Failed to parse TOML config at ${configPath}: ${err.message}`);
  }

  if (!isPlainObject(parsed)) {
    throw new Error(`Config at ${configPath} must be a TOML object.`);
  }

  return {
    configPath,
    configDirectory: path.dirname(configPath),
    configText,
    parsed,
  };
}

function readToolsFromConfig(configPathArg) {
  const config = readConfigFile(configPathArg);
  const toolsTable = config.parsed.tools;
  const tools = {};

  if (toolsTable === undefined) {
    return {
      configPath: config.configPath,
      configDirectory: config.configDirectory,
      configText: config.configText,
      tools,
    };
  }

  if (!isPlainObject(toolsTable)) {
    throw new Error(`[tools] in ${config.configPath} must be a TOML table.`);
  }

  for (const [aliasRaw, specifierRaw] of Object.entries(toolsTable)) {
    const alias = normalizeAlias(aliasRaw, config.configPath);
    const specifier = normalizeSpecifier(specifierRaw, config.configPath, alias);
    tools[alias] = specifier;
  }

  return {
    configPath: config.configPath,
    configDirectory: config.configDirectory,
    configText: config.configText,
    tools,
  };
}

function buildToolsSectionLines(tools) {
  const aliases = Object.keys(tools).sort((a, b) => a.localeCompare(b));
  const lines = ["[tools]"];
  for (const alias of aliases) {
    lines.push(`${alias} = ${JSON.stringify(tools[alias])}`);
  }
  return lines;
}

function isToolsHeaderLine(line) {
  return /^\s*\[tools\]\s*(#.*)?$/.test(line);
}

function isAnySectionHeaderLine(line) {
  return /^\s*\[\[[^\]]+\]\]\s*(#.*)?$/.test(line) || /^\s*\[[^\[\]]+\]\s*(#.*)?$/.test(line);
}

function upsertToolsSection(configText, tools) {
  const sectionLines = buildToolsSectionLines(tools);
  const lines = String(configText || "").split(/\r?\n/);

  let toolsSectionStart = -1;
  for (let index = 0; index < lines.length; index += 1) {
    if (isToolsHeaderLine(lines[index])) {
      toolsSectionStart = index;
      break;
    }
  }

  if (toolsSectionStart === -1) {
    const trimmed = String(configText || "").trimEnd();
    const prefix = trimmed ? `${trimmed}\n\n` : "";
    return `${prefix}${sectionLines.join("\n")}\n`;
  }

  let toolsSectionEnd = lines.length;
  for (let index = toolsSectionStart + 1; index < lines.length; index += 1) {
    if (isAnySectionHeaderLine(lines[index])) {
      toolsSectionEnd = index;
      break;
    }
  }

  const before = lines.slice(0, toolsSectionStart);
  const after = lines.slice(toolsSectionEnd);
  const merged = [...before, ...sectionLines];

  if (after.length > 0) {
    if (merged.length > 0 && merged[merged.length - 1].trim() !== "") {
      merged.push("");
    }
    merged.push(...after);
  }

  const output = merged.join("\n");
  return output.endsWith("\n") ? output : `${output}\n`;
}

function writeRokitManifest(projectDir, tools) {
  const targetDirectory = path.resolve(projectDir || ".");
  const manifestPath = path.join(targetDirectory, "rokit.toml");
  const lines = [
    "# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.",
    "# For more information, see https://github.com/rojo-rbx/rokit",
    "#",
    "# This file is auto-generated by Sof from [tools] in sof.toml.",
    "# Do not edit this file directly.",
    "",
    ...buildToolsSectionLines(tools),
    "",
  ];

  // Only rewritten when the tools changed, so editors and file watchers see no churn.
  const text = lines.join("\n");
  const changed = !fs.existsSync(manifestPath) || fs.readFileSync(manifestPath, "utf8") !== text;
  if (changed) {
    fs.writeFileSync(manifestPath, text, "utf8");
  }
  return { manifestPath, changed };
}

function addToolToConfig(configPathArg, aliasRaw, specifierRaw) {
  const config = readToolsFromConfig(configPathArg);
  const alias = normalizeAlias(aliasRaw, config.configPath);
  const specifier = normalizeSpecifier(specifierRaw, config.configPath, alias);

  const replaced = Object.prototype.hasOwnProperty.call(config.tools, alias);
  config.tools[alias] = specifier;

  const updatedText = upsertToolsSection(config.configText, config.tools);
  fs.writeFileSync(config.configPath, updatedText, "utf8");

  return {
    configPath: config.configPath,
    configDirectory: config.configDirectory,
    alias,
    specifier,
    replaced,
    tools: { ...config.tools },
  };
}

function prepareRokitManifest(configPathArg) {
  const config = readToolsFromConfig(configPathArg);
  const written = writeRokitManifest(config.configDirectory, config.tools);
  return {
    configPath: config.configPath,
    configDirectory: config.configDirectory,
    tools: config.tools,
    rokitManifestPath: written.manifestPath,
    manifestChanged: written.changed,
  };
}

module.exports = {
  addToolToConfig,
  prepareRokitManifest,
  readToolsFromConfig,
  writeRokitManifest,
};
