"use strict";

// sof.tools.lock: the sha256 of the release asset each tool was installed from, per platform.
// Optional (create it with `sof run tools lock`, commit it). Once it exists, every install is
// checked against it, so a release that was changed after you locked it is refused rather than
// run. Tools have different files on each platform, so each platform records its own line.
//
//   [[tool]]
//   name = "rojo-rbx/rojo"
//   version = "7.6.1"
//   platform = "windows-x64"
//   asset = "rojo-7.6.1-windows-x86_64.zip"
//   sha256 = "..."

const fs = require("fs");
const path = require("path");
const toml = require("smol-toml");

const LOCK_FILE_NAME = "sof.tools.lock";
const FIELDS = ["name", "version", "platform", "asset", "sha256"];

function currentPlatform() {
  const osName = { win32: "windows", darwin: "macos", linux: "linux" }[process.platform] || process.platform;
  return `${osName}-${process.arch}`;
}

function lockPathFor(configPath) {
  return path.join(path.dirname(configPath), LOCK_FILE_NAME);
}

function toolKey(spec) {
  return `${spec.owner}/${spec.repo}`.toLowerCase();
}

function readToolsLock(lockPath) {
  if (!fs.existsSync(lockPath)) {
    return { exists: false, entries: [] };
  }

  let parsed;
  try {
    parsed = toml.parse(fs.readFileSync(lockPath, "utf8"));
  } catch (err) {
    throw new Error(`Failed to parse ${lockPath}: ${err.message}`);
  }

  const raw = parsed.tool === undefined ? [] : parsed.tool;
  if (!Array.isArray(raw)) {
    throw new Error(`${lockPath}: "tool" must be an array of tables.`);
  }

  const entries = raw.map((entry, index) => {
    for (const field of FIELDS) {
      if (typeof (entry || {})[field] !== "string" || entry[field].trim() === "") {
        throw new Error(`${lockPath} [[tool]] entry #${index + 1}: "${field}" must be a non-empty string.`);
      }
    }
    return Object.fromEntries(FIELDS.map((field) => [field, entry[field].trim()]));
  });

  return { exists: true, entries };
}

function findLockEntry(lock, spec, platform = currentPlatform()) {
  return (
    lock.entries.find(
      (entry) => entry.name.toLowerCase() === toolKey(spec) && entry.version === spec.version && entry.platform === platform
    ) || null
  );
}

function quote(value) {
  return JSON.stringify(String(value));
}

function writeToolsLock(lockPath, entries) {
  const sorted = entries
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version) || a.platform.localeCompare(b.platform));

  const lines = ["# Auto-generated by sof run tools. Do not edit.", ""];
  for (const entry of sorted) {
    lines.push("[[tool]]", ...FIELDS.map((field) => `${field} = ${quote(entry[field])}`), "");
  }

  // Left alone when nothing changed, so file watchers don't fire on a no-op install.
  const text = `${lines.join("\n")}\n`;
  if (!fs.existsSync(lockPath) || fs.readFileSync(lockPath, "utf8") !== text) {
    fs.writeFileSync(lockPath, text, "utf8");
  }
}

// The lock after an install: lines for tools (at the versions) the config still lists are kept,
// this platform's line is set from what was just installed, and everything else is dropped.
function mergeLockEntries(existing, installed, specs) {
  const wanted = new Set(specs.map((spec) => `${toolKey(spec)}@${spec.version}`));
  const platform = currentPlatform();
  const entries = existing.filter((entry) => wanted.has(`${entry.name.toLowerCase()}@${entry.version}`));

  for (const { spec, record } of installed) {
    if (!record) {
      continue;
    }

    const entry = { name: toolKey(spec), version: spec.version, platform, asset: record.asset, sha256: record.sha256 };
    const index = entries.findIndex(
      (candidate) => candidate.name.toLowerCase() === entry.name && candidate.version === entry.version && candidate.platform === platform
    );
    if (index === -1) {
      entries.push(entry);
    } else {
      entries[index] = entry;
    }
  }
  return entries;
}

module.exports = {
  LOCK_FILE_NAME,
  currentPlatform,
  findLockEntry,
  lockPathFor,
  mergeLockEntries,
  readToolsLock,
  toolKey,
  writeToolsLock,
};
